# Generated by Django 6.0.3 on 2026-03-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhaven", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="username",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
