# Generated by Django 6.0.3 on 2026-03-30 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhaven", "0002_alter_customer_email_alter_customer_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="care_instructions",
            field=models.TextField(default="No care instructions available"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plant",
            name="description",
            field=models.TextField(default="Not available"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plant",
            name="size",
            field=models.CharField(default="Not available", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plant",
            name="slug",
            field=models.SlugField(default="Not available", unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plant",
            name="stock",
            field=models.CharField(max_length=50),
        ),
    ]
