# Generated by Django 6.0.3 on 2026-03-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "greenhaven",
            "0003_plant_care_instructions_plant_description_plant_size_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plant",
            name="care_instructions",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="size",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="plant",
            name="slug",
            field=models.SlugField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="stock",
            field=models.CharField(default="In Stock", max_length=50),
        ),
    ]
