# Generated by Django 6.0.3 on 2026-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhaven", "0004_alter_plant_care_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart_item",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="plant",
            name="care_instructions",
            field=models.TextField(default="No care instructions available"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(default="No description available"),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="plant",
            name="size",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="plant",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="plant",
            name="stock",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name="cart_item",
            unique_together={("cart", "plant")},
        ),
    ]
