# Generated by Django 6.0.3 on 2026-04-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("greenhaven", "0006_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="status",
            field=models.CharField(default="Active", max_length=20),
        ),
        migrations.AddField(
            model_name="cart",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
